# Generated by Django 4.0.4 on 2022-05-31 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genus', '0001_initial'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_num', models.CharField(blank=True, help_text='도입번호', max_length=40, null=True)),
                ('used_scientific_name', models.CharField(blank=True, help_text='도입학명', max_length=100, null=True)),
                ('plant_name', models.CharField(blank=True, help_text='국명', max_length=40, null=True)),
                ('microscope', models.BooleanField(blank=True, default=True, help_text='현미경(단립, 복립)', null=True)),
                ('seed_length', models.FloatField(blank=True, help_text='종자길이(mm)', null=True)),
                ('seed_length_error', models.FloatField(blank=True, help_text='종자길이오차', null=True)),
                ('seed_width', models.FloatField(blank=True, help_text='종자너비(mm)', null=True)),
                ('seed_width_error', models.FloatField(blank=True, help_text='종자너비오차', null=True)),
                ('note', models.TextField(blank=True, help_text='비고', null=True)),
                ('family', models.ForeignKey(blank=True, help_text='과명/과국명', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='family.family')),
                ('genus', models.ForeignKey(blank=True, help_text='속명/속국명', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genus', to='genus.genus')),
            ],
        ),
    ]
