# Generated by Django 4.0.4 on 2022-06-02 02:20

from django.db import migrations, models
import django.db.models.deletion
import seed.models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='이미지', null=True, upload_to=seed.models.image_upload_path)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seed.seed')),
            ],
        ),
    ]
