# Generated by Django 4.0.4 on 2022-06-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0002_seedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='grain',
            field=models.CharField(choices=[('sg', '단립'), ('dg', '복립')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
