# Generated by Django 4.0.4 on 2022-06-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0003_seed_grain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='grain',
            field=models.CharField(choices=[('단립', 'sg'), ('복립', 'dg')], max_length=2),
        ),
    ]
