# Generated by Django 4.0.4 on 2022-06-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0004_alter_seed_grain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='grain',
            field=models.CharField(choices=[('sg', '단립'), ('dg', '복립')], max_length=2),
        ),
    ]
