# Generated by Django 4.0.4 on 2022-06-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0003_alter_seed_user'),
        ('seed', '0005_alter_seed_grain'),
    ]

    operations = [
    ]
