# Generated by Django 4.0.4 on 2022-06-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seed', '0007_alter_seed_grain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='grain',
            field=models.CharField(blank=True, choices=[('sg', '단립'), ('dg', '복립')], help_text='단립/복립', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='microscope',
            field=models.BooleanField(blank=True, default=True, help_text='현미경', null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='user',
            field=models.ForeignKey(blank=True, help_text='생성한 사람', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
