# Generated by Django 4.0.4 on 2022-05-31 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genus_en', models.CharField(blank=True, help_text='속명', max_length=40, null=True)),
                ('genus_ko', models.CharField(blank=True, help_text='속국명', max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genus_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
