# Generated by Django 4.0.4 on 2022-05-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genus_en', models.CharField(blank=True, help_text='속명', max_length=40, null=True)),
                ('genus_ko', models.CharField(blank=True, help_text='속국명', max_length=40, null=True)),
            ],
        ),
    ]
